# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-25 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20170824_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', '未支付'), ('P', '已支付'), ('D', '已发货'), ('F', '已完成')], max_length=1, verbose_name='状态')),
                ('destination', models.CharField(max_length=100, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item', verbose_name='购买项目')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name_plural': '订单条目',
                'verbose_name': '订单条目',
            },
        ),
    ]
