# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='8a6fb3cb1d164048a1e88de035cc6350', editable=False, verbose_name='订单编号'),
        ),
    ]
