# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(editable=False, verbose_name='订单编号'),
        ),
    ]
