# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('price',), 'verbose_name': '商品购买项目', 'verbose_name_plural': '商品购买项目'},
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目描述'),
        ),
    ]
