# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170824_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('price',), 'verbose_name': '购买项目', 'verbose_name_plural': '购买项目'},
        ),
    ]
