/*
 *   user action constants
 *   user action constants
 *   user action constants
*/

const GET_TOKEN = 'GET_TOKEN';
const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';

const REMOVE_TOKEN = 'REMOVE_TOKEN';

const REGISTER = 'REGISTER';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR';

const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

const LOGOUT = 'LOGOUT';

export {
    GET_TOKEN,
    GET_TOKEN_SUCCESS,
    
    REMOVE_TOKEN,


    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_ERROR,

    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_ERROR,

    CHANGE_PASSWORD,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_ERROR,

    LOGOUT,
}